# Generated by Django 6.1 on 2026-08-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Obetald'), ('partly_paid', 'Delvis betald'), ('paid', 'Betald'), ('cancelled', 'Makulerad')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('swish', 'Swish'), ('cash', 'Kontant'), ('bank_transfer', 'Banköverföring'), ('other', 'Övrigt')], default='swish', max_length=20),
        ),
    ]
