# Generated by Django 6.1 on 2026-08-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_userprofile'),
        ('payments', '0002_alter_invoice_status_alter_payment_method'),
        ('people', '0002_remove_person_uniq_person_pnr_per_club_and_more'),
        ('scheduling', '0003_alter_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['club', 'status'], name='payments_in_club_id_1ff03b_idx'),
        ),
    ]
