# Generated by Django 6.1 on 2026-08-25 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='clubs.club')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('activity_type', models.CharField(choices=[('training', 'Training session'), ('competition', 'Competition'), ('meeting', 'Meeting')], max_length=20)),
                ('recurrence', models.CharField(choices=[('none', 'Never'), ('daily', 'Every day'), ('weekdays', 'Every weekday'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('weekday', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField(blank=True, help_text='Defaults to season start.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Defaults to season end.', null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_templates', to='clubs.club')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_templates', to='groups.group')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_templates', to='scheduling.season')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('activity_type', models.CharField(choices=[('training', 'Training session'), ('competition', 'Competition'), ('meeting', 'Meeting')], max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='clubs.club')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='groups.group')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='scheduling.activitytemplate')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='scheduling.season')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('club', 'name'), name='uniq_season_per_club'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['club', 'date'], name='scheduling__club_id_2f9b3d_idx'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(condition=models.Q(('template__isnull', False)), fields=('template', 'date'), name='uniq_occurrence_per_template_and_date'),
        ),
    ]
