# Generated by Django 6.1 on 2026-08-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_manually_edited',
            field=models.BooleanField(default=False),
        ),
    ]
