# Generated by Django 6.1 on 2026-08-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_activity_is_manually_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('training', 'Träningspass'), ('competition', 'Tävling'), ('meeting', 'Möte')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activitytemplate',
            name='activity_type',
            field=models.CharField(choices=[('training', 'Träningspass'), ('competition', 'Tävling'), ('meeting', 'Möte')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activitytemplate',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Aldrig'), ('daily', 'Varje dag'), ('weekdays', 'Vardagar'), ('weekly', 'Varje vecka'), ('monthly', 'Varje månad')], default='weekly', max_length=20),
        ),
        migrations.AlterField(
            model_name='activitytemplate',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Måndag'), (1, 'Tisdag'), (2, 'Onsdag'), (3, 'Torsdag'), (4, 'Fredag'), (5, 'Lördag'), (6, 'Söndag')], null=True),
        ),
    ]
