# Generated by Django 6.1 on 2026-08-26 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='club_backgrounds/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='club_logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AddField(
            model_name='club',
            name='primary_color',
            field=models.CharField(default='#0d6efd', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a color as #RRGGBB.', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AddField(
            model_name='club',
            name='secondary_color',
            field=models.CharField(default='#212529', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a color as #RRGGBB.', regex='^#[0-9a-fA-F]{6}$')]),
        ),
    ]
