# Generated by Django 6.1 on 2026-08-25 21:13

import django.db.models.deletion
import people.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_groups', to='clubs.club')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('personnummer', models.CharField(help_text='Stored as YYYYMMDDXXXX.', max_length=12, validators=[people.models.validate_personnummer])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary')], max_length=20)),
                ('street_address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_mobile', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('allergy', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='clubs.club')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('paused', 'Paused')], default='active', max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('partly_paid', 'Partly paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20)),
                ('start_date', models.DateField()),
                ('disability', models.CharField(blank=True, max_length=500)),
                ('photo_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='GuardianRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarded_by', to='people.person')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_of', to='people.person')),
            ],
            options={
                'ordering': ['child__last_name', 'child__first_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_groups', models.ManyToManyField(blank=True, related_name='staff_members', to='people.admingroup')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='people.person')),
            ],
        ),
        migrations.AddConstraint(
            model_name='admingroup',
            constraint=models.UniqueConstraint(fields=('club', 'name'), name='uniq_admingroup_per_club'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('club', 'personnummer'), name='uniq_person_pnr_per_club'),
        ),
        migrations.AddConstraint(
            model_name='guardianrelation',
            constraint=models.UniqueConstraint(fields=('guardian', 'child'), name='uniq_guardian_child'),
        ),
    ]
