# Generated by Django 6.1 on 2026-08-26 20:06

import people.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_background_image_club_logo_club_primary_color_and_more'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='person',
            name='uniq_person_pnr_per_club',
        ),
        migrations.AddField(
            model_name='guardianrelation',
            name='relation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='member_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Betald'), ('partly_paid', 'Delvis betald'), ('unpaid', 'Obetald')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('inactive', 'Inaktiv'), ('paused', 'Pausad')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Man'), ('female', 'Kvinna'), ('non_binary', 'Icke-binär')], max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='personnummer',
            field=models.CharField(blank=True, help_text='Stored as YYYYMMDDXXXX, or YYYYMMDD**** when partially known.', max_length=12, null=True, validators=[people.models.validate_personnummer]),
        ),
        migrations.AlterField(
            model_name='person',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='street_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('personnummer__endswith', '****'), _negated=True), fields=('club', 'personnummer'), name='uniq_person_pnr_per_club'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('member_number', ''), _negated=True), fields=('club', 'member_number'), name='uniq_person_member_number_per_club'),
        ),
    ]
