# Generated by Django 6.1 on 2026-08-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Närvarande'), ('late', 'Sen'), ('absent', 'Frånvarande'), ('excused', 'Godkänd frånvaro')], default='present', max_length=20),
        ),
    ]
